language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: owl-93-github
    token:
      secure: 052f37aa4c1ad2f8fcea8fe0d1d513667440e55b
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
      
